CREATE TABLE `sc`.`userinfo` (
  `OPEN_ID` VARCHAR(100) NOT NULL,
  `AVATARURL` VARCHAR(500) NOT NULL,
  `CITY` VARCHAR(45) NULL,
  `COUNTRY` VARCHAR(45) NULL,
  `GENDER` INT NULL,
  `LANGUAGE` VARCHAR(45) NULL,
  `NICKNAME` NVARCHAR(200) NOT NULL,
  `PROVINCE` VARCHAR(45) NULL,
  UNIQUE INDEX `OPEN_ID_UNIQUE` (`OPEN_ID` ASC) VISIBLE,
  PRIMARY KEY (`OPEN_ID`));
  
  
  
  
  
CREATE TABLE `sc`.`user` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `OPEN_ID` VARCHAR(100) NOT NULL,
  `PHONE` VARCHAR(45) NULL,
  `CREATED_DATE` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `OPEN_ID_UNIQUE` (`OPEN_ID` ASC) VISIBLE,
  UNIQUE INDEX `PHONE_UNIQUE` (`PHONE` ASC) VISIBLE);
  
  
  
  
CREATE TABLE `sc`.`class` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `DESC` VARCHAR(500) NULL,
  `LEVEL` INT NOT NULL DEFAULT 1,
  `TYPE` INT NOT NULL DEFAULT 1,
  `CREATED_BY` INT NOT NULL,
  `CREATED_DATE` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`ID`));


